# Generated by Django 3.2.9 on 2021-11-02 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SnijdbaarVlees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=200)),
                ('cat', models.CharField(max_length=50)),
                ('aantal', models.IntegerField()),
            ],
        ),
    ]
